# Generated by Django 5.2.17 on 2026-10-02 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Competencia / Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Evaluación / Simulacro')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o Instrucciones')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha y Hora de Apertura')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha y Hora de Cierre')),
                ('tiempo_limite_minutos', models.IntegerField(verbose_name='Tiempo Límite (Minutos)')),
                ('intentos_permitidos', models.IntegerField(default=1, verbose_name='Intentos Permitidos')),
                ('calificacion_maxima', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Calificación Máxima')),
                ('calificacion_aprobacion', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Calificación Mínima Aprobatoria')),
                ('mezclar_preguntas', models.BooleanField(default=False, verbose_name='Mezclar Preguntas Aleatoriamente')),
                ('mezclar_respuestas', models.BooleanField(default=False, verbose_name='Mezclar Respuestas Aleatoriamente')),
                ('permitir_revision', models.BooleanField(default=True, verbose_name='Permitir Ver Retroalimentación tras Entrega')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Programado', 'Programado'), ('Disponible', 'Disponible'), ('Cerrado', 'Cerrado')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'db_table': 'cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Carga')),
                ('total_filas', models.IntegerField(default=0, verbose_name='Total Filas Evaluadas')),
                ('total_validas', models.IntegerField(default=0, verbose_name='Filas Válidas Importadas')),
                ('total_errores', models.IntegerField(default=0, verbose_name='Filas con Error')),
                ('detalle_log', models.TextField(blank=True, null=True, verbose_name='Bitácora Detallada de Validación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importación Masiva',
                'verbose_name_plural': 'Importaciones Masivas',
                'db_table': 'importaciones',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=120, verbose_name='Nombre del Estudiante')),
                ('codigo_estudiante', models.CharField(max_length=30, verbose_name='Código Institucional')),
                ('numero_intento', models.IntegerField(default=1, verbose_name='Número de Intento')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Finalización')),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje Obtenido')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación Final')),
                ('estado', models.CharField(choices=[('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='En Progreso', max_length=20, verbose_name='Estado de la Sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='intentos', to='simulador.cuestionario')),
            ],
            options={
                'verbose_name': 'Intento de Estudiante',
                'verbose_name_plural': 'Intentos de Estudiantes',
                'db_table': 'intentos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTIPLE', 'Opción Múltiple con Única Respuesta'), ('VERDADERO_FALSO', 'Verdadero / Falso')], default='MULTIPLE', max_length=20, verbose_name='Tipo de Pregunta')),
                ('texto_base', models.TextField(blank=True, null=True, verbose_name='Texto Base / Contexto de Lectura')),
                ('enunciado', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('retroalimentacion', models.TextField(blank=True, null=True, verbose_name='Retroalimentación Pedagógica')),
                ('puntaje_base', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puntaje Base')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preguntas', to='simulador.categoria', verbose_name='Categoría / Módulo')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Letra de Opción')),
                ('texto', models.TextField(verbose_name='Texto de la Alternativa')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la opción correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='simulador.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'db_table': 'opciones_respuesta',
            },
        ),
        migrations.CreateModel(
            name='CuestionarioPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de Aparición')),
                ('puntaje_ponderado', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puntaje Ponderado')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_preguntas', to='simulador.cuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuestionarios_asignados', to='simulador.pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de Cuestionario',
                'verbose_name_plural': 'Preguntas de Cuestionario',
                'db_table': 'cuestionario_preguntas',
                'ordering': ['orden'],
                'unique_together': {('cuestionario', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('puntaje_asignado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje Asignado')),
                ('marcada_revision', models.BooleanField(default=False, verbose_name='Marcada para Revisión')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simulador.intento')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.opcionrespuesta', verbose_name='Opción Seleccionada (NULL si omisión)')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='respuestas_evaluadas', to='simulador.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Intento',
                'verbose_name_plural': 'Respuestas de Intento',
                'db_table': 'respuestas_intento',
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
